# -*- coding: utf-8 -*-
"""
Evaluate a trained TPQ-Net checkpoint on the locked test split.

This script imports the model and data utilities from ``02_train_tpqnet.py`` so
the testing architecture stays exactly consistent with the training code.

Default workflow
----------------
1. Build DCT-3T:
   python 01_build_dct3.py

2. Train TPQ-Net:
   python 02_train_tpqnet.py

3. Test the best checkpoint:
   python 03_test_tpqnet.py

Outputs
-------
- test_metrics.json
- confusion_matrix.csv
- per_class_metrics.csv
- predictions.csv

Run this script from the repository root.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Mapping, Tuple

import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader


DEFAULT_TRAIN_SCRIPT = "./02_train_tpqnet.py"
DEFAULT_DATA_NPZ = "./generated/dct3/LFM_SEI_clean_iq__dct3_tau2_grid128_disp1.npz"
DEFAULT_SPLIT_NPZ = "./data/split_622.npz"
DEFAULT_CHECKPOINT = "./outputs/clean/best_model.pt"
DEFAULT_OUT_DIR = "./outputs/clean/test_results"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Evaluate TPQ-Net on the fixed test split."
    )
    parser.add_argument(
        "--train_script",
        type=str,
        default=DEFAULT_TRAIN_SCRIPT,
        help="Path to 02_train_tpqnet.py.",
    )
    parser.add_argument(
        "--data_npz",
        type=str,
        default=DEFAULT_DATA_NPZ,
        help="DCT-3T dataset generated by 01_build_dct3.py.",
    )
    parser.add_argument(
        "--split_npz",
        type=str,
        default=DEFAULT_SPLIT_NPZ,
        help="Locked 6:2:2 split file.",
    )
    parser.add_argument(
        "--checkpoint",
        type=str,
        default=DEFAULT_CHECKPOINT,
        help="TPQ-Net checkpoint, normally best_model.pt.",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default=DEFAULT_OUT_DIR,
        help="Directory used to save test results.",
    )
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument(
        "--device",
        choices=["auto", "cpu", "cuda"],
        default="auto",
        help="Evaluation device.",
    )
    parser.add_argument(
        "--use_amp",
        action="store_true",
        default=False,
        help="Enable CUDA automatic mixed precision during inference.",
    )
    return parser.parse_args()


def load_train_module(script_path: str):
    """Load 02_train_tpqnet.py even though its filename starts with a number."""
    path = Path(script_path).resolve()
    if not path.is_file():
        raise FileNotFoundError(f"Training script not found: {path}")

    module_name = "tpqnet_train_module"
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"Cannot create import specification for: {path}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = module
    spec.loader.exec_module(module)
    return module


def select_device(device_arg: str) -> torch.device:
    if device_arg == "cpu":
        return torch.device("cpu")
    if device_arg == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("--device cuda was requested, but CUDA is unavailable.")
        return torch.device("cuda")
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def load_checkpoint(train_module, checkpoint_path: str, device: torch.device) -> Dict[str, Any]:
    path = Path(checkpoint_path)
    if not path.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {path}")

    checkpoint = train_module.torch_load_compat(path, map_location=device)
    if not isinstance(checkpoint, dict):
        raise TypeError(
            "Checkpoint must be a dictionary containing model_state_dict "
            "or a raw state dictionary."
        )
    return checkpoint


def extract_state_dict(checkpoint: Mapping[str, Any]) -> Mapping[str, torch.Tensor]:
    if "model_state_dict" in checkpoint:
        state_dict = checkpoint["model_state_dict"]
    elif "state_dict" in checkpoint:
        state_dict = checkpoint["state_dict"]
    else:
        # Support a raw model state dictionary.
        state_dict = checkpoint

    if not isinstance(state_dict, Mapping):
        raise TypeError("The checkpoint does not contain a valid model state dictionary.")

    cleaned: Dict[str, torch.Tensor] = {}
    prefixes = ("module.", "_orig_mod.")
    for key, value in state_dict.items():
        new_key = str(key)
        for prefix in prefixes:
            if new_key.startswith(prefix):
                new_key = new_key[len(prefix):]
        cleaned[new_key] = value
    return cleaned


def cfg_value(cfg: Mapping[str, Any], key: str, default: Any) -> Any:
    value = cfg.get(key, default)
    return default if value is None else value


def build_model(
    train_module,
    checkpoint: Mapping[str, Any],
    in_channels: int,
    num_classes: int,
    device: torch.device,
):
    cfg = checkpoint.get("config", {})
    if not isinstance(cfg, Mapping):
        cfg = {}

    model = train_module.TPQNet(
        in_channels=in_channels,
        num_classes=num_classes,
        frontend_stem_channels=int(cfg_value(cfg, "frontend_stem_channels", 16)),
        stage_channels=tuple(cfg_value(cfg, "stage_channels", [64, 128, 192, 256])),
        stage_depths=tuple(cfg_value(cfg, "stage_depths", [1, 2, 2, 2])),
        branch_dilations=tuple(cfg_value(cfg, "branch_dilations", [1, 2, 4])),
        dropout=float(cfg_value(cfg, "dropout", 0.10)),
        fc_dim=int(cfg_value(cfg, "fc_dim", 256)),
        neck_type=str(cfg_value(cfg, "neck_type", "qgbn")),
        qgbn_hidden=int(cfg_value(cfg, "qgbn_hidden", 64)),
        qgbn_init_bias=float(cfg_value(cfg, "qgbn_init_bias", -2.0)),
        qgbn_gate_max=float(cfg_value(cfg, "qgbn_gate_max", 0.75)),
        qacm_scale=float(cfg_value(cfg, "qacm_scale", 24.0)),
        qacm_base_margin=float(cfg_value(cfg, "qacm_base_margin", 0.12)),
        qacm_strength=float(cfg_value(cfg, "qacm_strength", 0.15)),
        qacm_quality_ema=float(cfg_value(cfg, "qacm_quality_ema", 0.99)),
        qacm_quality_clip=float(cfg_value(cfg, "qacm_quality_clip", 1.0)),
        qacm_min_margin=float(cfg_value(cfg, "qacm_min_margin", 0.04)),
        qacm_max_margin=float(cfg_value(cfg, "qacm_max_margin", 0.20)),
        use_hrec=bool(cfg_value(cfg, "use_hrec", True)),
        hrec_groups=int(cfg_value(cfg, "hrec_groups", 8)),
        hrec_gamma_init=float(cfg_value(cfg, "hrec_gamma_init", 0.0)),
        hrec_stage3_gamma_max=float(cfg_value(cfg, "hrec_stage3_gamma_max", 0.25)),
        hrec_stage4_gamma_max=float(cfg_value(cfg, "hrec_stage4_gamma_max", 0.50)),
        use_lka=bool(cfg_value(cfg, "use_lka", True)),
        use_ctsf=bool(cfg_value(cfg, "use_ctsf", True)),
    ).to(device)

    state_dict = extract_state_dict(checkpoint)
    model.load_state_dict(state_dict, strict=True)
    model.eval()
    return model, dict(cfg)


def get_normalization_stats(
    checkpoint: Mapping[str, Any],
    x_train: np.ndarray,
    train_module,
) -> Dict[str, np.ndarray]:
    saved = checkpoint.get("normalization_stats")
    if isinstance(saved, Mapping) and "mean" in saved and "std" in saved:
        mean = np.asarray(saved["mean"], dtype=np.float32)
        std = np.asarray(saved["std"], dtype=np.float32)
        return {"mean": mean, "std": std}

    print("[WARN ] normalization_stats not found in checkpoint; recomputing from train split.")
    return train_module.compute_train_channel_stats(x_train)


def build_test_loader(
    train_module,
    x: np.ndarray,
    y: np.ndarray,
    idx_train: np.ndarray,
    idx_test: np.ndarray,
    checkpoint: Mapping[str, Any],
    checkpoint_cfg: Mapping[str, Any],
    batch_size: int,
    num_workers: int,
) -> Tuple[DataLoader, Dict[str, np.ndarray], str]:
    normalization = str(checkpoint_cfg.get("normalization", "std"))
    stats = get_normalization_stats(
        checkpoint=checkpoint,
        x_train=x[idx_train],
        train_module=train_module,
    )

    x_test = train_module.apply_channel_normalization_np(
        x[idx_test],
        stats,
        mode=normalization,
    )
    y_test = y[idx_test]

    dataset = train_module.NumpyTensorDataset(x_test, y_test)
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=False,
        drop_last=False,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
        persistent_workers=False,
        worker_init_fn=(
            train_module.make_worker_init_fn(42) if num_workers > 0 else None
        ),
    )
    return loader, stats, normalization


def compute_confusion_matrix(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    num_classes: int,
) -> np.ndarray:
    matrix = np.zeros((num_classes, num_classes), dtype=np.int64)
    for true_label, pred_label in zip(y_true, y_pred):
        matrix[int(true_label), int(pred_label)] += 1
    return matrix


def compute_per_class_metrics(confusion: np.ndarray) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for cls in range(confusion.shape[0]):
        tp = float(confusion[cls, cls])
        fp = float(confusion[:, cls].sum() - tp)
        fn = float(confusion[cls, :].sum() - tp)
        support = int(confusion[cls, :].sum())

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
        f1 = (
            2.0 * precision * recall / (precision + recall)
            if (precision + recall) > 0
            else 0.0
        )
        rows.append(
            {
                "class": cls,
                "precision": precision,
                "recall": recall,
                "f1": f1,
                "support": support,
            }
        )
    return rows


def evaluate(
    model,
    loader: DataLoader,
    device: torch.device,
    use_amp: bool,
) -> Tuple[float, np.ndarray, np.ndarray, np.ndarray]:
    total_loss = 0.0
    total_num = 0
    all_true: List[np.ndarray] = []
    all_pred: List[np.ndarray] = []
    all_confidence: List[np.ndarray] = []

    amp_enabled = bool(use_amp and device.type == "cuda")

    with torch.inference_mode():
        for xb, yb in loader:
            xb = xb.to(device, non_blocking=True)
            yb = yb.to(device, non_blocking=True)

            if amp_enabled:
                with torch.autocast(device_type="cuda", dtype=torch.float16):
                    logits = model(xb, targets=None)
                    loss = F.cross_entropy(logits, yb)
            else:
                logits = model(xb, targets=None)
                loss = F.cross_entropy(logits, yb)

            probabilities = torch.softmax(logits, dim=1)
            confidence, predictions = probabilities.max(dim=1)

            batch_size = int(yb.size(0))
            total_loss += float(loss.item()) * batch_size
            total_num += batch_size

            all_true.append(yb.cpu().numpy())
            all_pred.append(predictions.cpu().numpy())
            all_confidence.append(confidence.cpu().numpy())

    if total_num == 0:
        raise RuntimeError("The test loader is empty.")

    return (
        total_loss / total_num,
        np.concatenate(all_true).astype(np.int64, copy=False),
        np.concatenate(all_pred).astype(np.int64, copy=False),
        np.concatenate(all_confidence).astype(np.float32, copy=False),
    )


def save_json(obj: Dict[str, Any], path: Path) -> None:
    def converter(value):
        if isinstance(value, np.ndarray):
            return value.tolist()
        if isinstance(value, (np.integer,)):
            return int(value)
        if isinstance(value, (np.floating,)):
            return float(value)
        raise TypeError(f"Object of type {type(value).__name__} is not JSON serializable")

    with path.open("w", encoding="utf-8") as file:
        json.dump(obj, file, ensure_ascii=False, indent=2, default=converter)


def save_confusion_matrix(matrix: np.ndarray, path: Path) -> None:
    with path.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["true\\pred"] + [f"class_{i}" for i in range(matrix.shape[1])])
        for class_id, row in enumerate(matrix):
            writer.writerow([f"class_{class_id}"] + row.tolist())


def save_dict_rows(rows: List[Dict[str, Any]], path: Path) -> None:
    if not rows:
        raise ValueError(f"No rows to save: {path}")
    with path.open("w", encoding="utf-8-sig", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    train_module = load_train_module(args.train_script)
    train_module.seed_everything(42)
    device = select_device(args.device)

    print("=" * 100)
    print("[MODEL] TPQ-Net independent test")
    print(f"[PATH ] train_script = {args.train_script}")
    print(f"[PATH ] data_npz     = {args.data_npz}")
    print(f"[PATH ] split_npz    = {args.split_npz}")
    print(f"[PATH ] checkpoint   = {args.checkpoint}")
    print(f"[PATH ] out_dir      = {out_dir}")
    print(f"[ENV  ] device       = {device}")
    print("=" * 100)

    loaded = train_module.load_data_npz(args.data_npz)
    x, y = loaded.x, loaded.y

    idx_train, idx_val, idx_test = train_module.load_locked_splits(args.split_npz)
    train_module.validate_split_indices(
        idx_train,
        idx_val,
        idx_test,
        n_total=int(x.shape[0]),
    )

    unique_labels = np.unique(y)
    num_classes = int(unique_labels.size)
    expected_labels = np.arange(num_classes, dtype=np.int64)
    if not np.array_equal(unique_labels, expected_labels):
        raise ValueError(
            f"Labels must be contiguous integers from 0 to {num_classes - 1}; "
            f"found {unique_labels.tolist()}."
        )

    checkpoint = load_checkpoint(train_module, args.checkpoint, device)
    model, checkpoint_cfg = build_model(
        train_module=train_module,
        checkpoint=checkpoint,
        in_channels=int(x.shape[1]),
        num_classes=num_classes,
        device=device,
    )

    test_loader, stats, normalization = build_test_loader(
        train_module=train_module,
        x=x,
        y=y,
        idx_train=idx_train,
        idx_test=idx_test,
        checkpoint=checkpoint,
        checkpoint_cfg=checkpoint_cfg,
        batch_size=args.batch_size,
        num_workers=args.num_workers,
    )

    test_loss, y_true, y_pred, confidence = evaluate(
        model=model,
        loader=test_loader,
        device=device,
        use_amp=args.use_amp,
    )

    metrics = train_module.compute_classification_metrics(y_true, y_pred)
    confusion = compute_confusion_matrix(y_true, y_pred, num_classes)
    per_class = compute_per_class_metrics(confusion)

    prediction_rows: List[Dict[str, Any]] = []
    for global_index, true_label, pred_label, conf in zip(
        idx_test, y_true, y_pred, confidence
    ):
        prediction_rows.append(
            {
                "global_index": int(global_index),
                "true_label": int(true_label),
                "pred_label": int(pred_label),
                "confidence": float(conf),
                "correct": int(true_label == pred_label),
            }
        )

    hrec_stage3_alpha = (
        model.hrec_stage3.effective_alpha_value()
        if hasattr(model.hrec_stage3, "effective_alpha_value")
        else None
    )
    hrec_stage4_alpha = (
        model.hrec_stage4.effective_alpha_value()
        if hasattr(model.hrec_stage4, "effective_alpha_value")
        else None
    )

    summary = {
        "method_name": "TPQ-Net",
        "data_npz": str(Path(args.data_npz)),
        "split_npz": str(Path(args.split_npz)),
        "checkpoint": str(Path(args.checkpoint)),
        "checkpoint_epoch": checkpoint.get("epoch"),
        "checkpoint_best_val_bAcc": checkpoint.get("best_val_bacc"),
        "device": str(device),
        "normalization": normalization,
        "train_channel_mean": stats["mean"],
        "train_channel_std": stats["std"],
        "n_test": int(len(idx_test)),
        "num_classes": num_classes,
        "test_loss": float(test_loss),
        "accuracy": float(metrics["acc"]),
        "balanced_accuracy": float(metrics["bAcc"]),
        "macro_precision": float(metrics["macro_precision"]),
        "macro_f1": float(metrics["macro_f1"]),
        "cohen_kappa": float(metrics["kappa"]),
        "hrec_stage3_effective_alpha": hrec_stage3_alpha,
        "hrec_stage4_effective_alpha": hrec_stage4_alpha,
    }

    save_json(summary, out_dir / "test_metrics.json")
    save_confusion_matrix(confusion, out_dir / "confusion_matrix.csv")
    save_dict_rows(per_class, out_dir / "per_class_metrics.csv")
    save_dict_rows(prediction_rows, out_dir / "predictions.csv")

    print(
        f"[TEST ] loss={test_loss:.4f} | "
        f"Acc={metrics['acc']:.4f} | "
        f"bAcc={metrics['bAcc']:.4f} | "
        f"Macro-P={metrics['macro_precision']:.4f} | "
        f"Macro-F1={metrics['macro_f1']:.4f} | "
        f"Kappa={metrics['kappa']:.4f}"
    )
    print(f"[SAVE ] {out_dir / 'test_metrics.json'}")
    print(f"[SAVE ] {out_dir / 'confusion_matrix.csv'}")
    print(f"[SAVE ] {out_dir / 'per_class_metrics.csv'}")
    print(f"[SAVE ] {out_dir / 'predictions.csv'}")
    print("=" * 100)


if __name__ == "__main__":
    main()
